// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1024.Emmet.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc1024.Emmet.subsystems.Drivetrain;
import org.usfirst.frc1024.Emmet.subsystems.Lifter;

/**
 *
 */
public class  ConsecutiveStack1 extends Command {

    public ConsecutiveStack1() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	//make sure you're not moving
    	if(Drivetrain.rightEncoder.getRate()==0 && Drivetrain.leftEncoder.getRate()==0 && Drivetrain.slideEncoder1.getRate()==0 && Drivetrain.slideEncoder2.getRate()==0){
    	Lifter.LiftMotors(1); //check where you are and go down to level 1
    	Lifter.LiftMotors(0); //go down to grab totes
    	Lifter.LiftMotors(1); //set to end state
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
