// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1024.Emmet.subsystems;

import org.usfirst.frc1024.Emmet.RobotMap;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Gripper extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Compressor compressor = RobotMap.gripperCompressor;
    public static DoubleSolenoid rightArm = RobotMap.gripperRightArm;
    public static DoubleSolenoid leftArm = RobotMap.gripperLeftArm;
    static CANTalon leftIntake = RobotMap.gripperLeftIntake;
    static CANTalon rightIntake = RobotMap.gripperRightIntake;
    DigitalInput binDetector = RobotMap.gripperBinDetector;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    public static void Open(){
    	rightArm.set(DoubleSolenoid.Value.kForward);
    	leftArm.set(DoubleSolenoid.Value.kForward);
    }
    public static void Close(){
    	rightArm.set(DoubleSolenoid.Value.kReverse);
    	leftArm.set(DoubleSolenoid.Value.kReverse);
    }
}

